# Generated by Django 4.2.23 on 2026-04-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_receipt_receipt_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='confidence',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='source',
            field=models.CharField(default='AI', max_length=20),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(default='Processing', max_length=20),
        ),
    ]
